@startuml
class Ocean {
    + Ocean()
    + Size : int <<get>>
    + NumPrey : int <<get>> <<set>>
    + NumObstacles : int <<get>> <<set>>
    + NumPredator : int <<get>> <<set>>
    + Init() : void
    + Update() : void
    + SyncNumbersOfFish() : void
    + AddPrey(num:int) : void
    + AddPrey() : void
    + AddPredator(num:int) : void
    + AddPredator() : void
    + AddObstacles(num:int) : void
    + AddObstacles() : void
    + GetEmptyNeighbor(c:Cell) : Movement
    + GetPreyNeighbor(c:Cell) : Movement
    + GetCellAt(coord:Coordinates) : Cell
    + AssignCellAt(coord:Coordinates, c:Cell) : void
    + MoveAnimals() : void
}
IShowKills <|-- Ocean
Ocean --> "killPlace" Coordinates
Ocean --> "victim" Image
Ocean --> "killer" Image
@enduml
