@startuml
class GamezoneManipulations {
    + {static} InitGamezone() : char[,]
    + {static} UpdatePositionOnGamezone(gamezone:char[,], spaceship:Spaceship, oldPosition:Position, attack:bool) : void
    + {static} DeletePosition(gamezone:char[,], oldPosition:Position) : void
}
@enduml
