@startuml
class CircleInSquare {
    + CircleInSquare(x:int, y:int, length:int)
    + CircleInSquare(sqr:Square)
    + <<override>> Resize(index:double) : void
    + <<override>> GetView() : PicItem[]
}
Square <|-- CircleInSquare
CircleInSquare --> "UseCircle" Circle
@enduml
