@startuml
class Figure {
    + Figure(squareToAdd:Square)
    + Figure(rectangleToAdd:Rectangle)
    + Figure(circleToAdd:Circle)
    + <<async>> MoveAsync(x:int, y:int) : Task
    + Resize(index:int) : void
}
Figure --> "FigureName" FigureList
Figure --> "ID" Guid
@enduml
