@startuml
class Picture {
    + <<const>> DEFAULT_FILENAME : string = "untitled"
    + Picture()
    + Picture(figures:Point[])
    + Picture(fileName:string)
    + Picture(fileName:string, figures:Point[])
    + FileName : string <<get>> <<set>>
    + Add(figureToAdd:Point) : void
    + Add(figureToAdd:Point[]) : void
    + Delete(figureToDelete:Point) : void
    + <<override>> Move(x:int, y:int) : void
    + <<override>> Resize(index:double) : void
    + <<override>> Rotate45() : void
    + <<override>> GetView() : PicItem[]
    + GetArea() : double
    + GetPerimeter() : int
}
Point <|-- Picture
IGeometrical <|-- Picture
@enduml
