@startuml
class Point {
    + Point(x:int, y:int, pictureOwner:Picture)
    + Point(pictureOwner:Picture)
    + CoordX : int <<get>> <<set>>
    + CoordY : int <<get>> <<set>>
    + UpdatePoint(x:int, y:int) : void
    + <<override>> Move(x:int, y:int) : void
}
Picture <|-- Point
Point --> "PictureOwner" Picture
@enduml
