@startuml
class Rectangle {
    + Rectangle(x:int, y:int, length:int, height:int)
    + Rectangle(newQuadrilateral:Quadrilateral, height:int)
    + heightOfRectangle : int <<get>> <<set>>
    + <<override>> Move(x:int, y:int) : void
    + <<override>> GetView() : PicItem[]
    + <<override>> GetArea() : double
    + <<override>> GetPerimeter() : int
}
Quadrilateral <|-- Rectangle
IGeometrical <|-- Rectangle
@enduml
