@startuml
class Square {
    + Square(x:int, y:int, length:int)
    + Square(newQuadrilateral:Quadrilateral)
    + GetArea() : double
    + GetPerimeter() : int
    + CompareTo(obj:object?) : int
}
Quadrilateral <|-- Square
IGeometrical <|-- Square
IComparable <|-- Square
@enduml
