@startuml
class Square {
    + Square(x:int, y:int, length:int)
    + Square(newQuadrilateral:Quadrilateral)
    + <<override>> Move(x:int, y:int) : void
    + <<override>> GetView() : PicItem[]
}
Quadrilateral <|-- Square
@enduml
