@startuml
class UI {
    + {static} DrawSquare(squareToDraw:Square, consoleClear:bool) : void
    + {static} DrawCircle(circleToDraw:Circle, consoleClear:bool) : void
    + {static} DrawPicture(pictureToDraw:Picture) : void
}
@enduml
