@startuml
class CheckPoint {
    + CheckPoint(x:int, y:int)
    + CheckPoint(coord:int)
    + CheckPoint(source:CheckPoint)
    + <<override>> Resize(delta:double) : void
    + <<override>> GetView() : PictItem[]
    + <<override>> ToString() : string
    + <<virtual>> Rotate45() : void
}
Figure2d <|-- CheckPoint
@enduml
