@startuml
class Group {
    + Group(groupName:string, startDate:DateTime, currentYear:int, groupSupervisor:Supervisor, groupSubjects:SubjectList[], studentsList:Student[], avrMarkOfGroup:double, groupSpecialization:Specialization)
    + Group(groupName:string, startDate:DateTime, currentYear:int, groupSupervisor:Supervisor, groupSpecialization:Specialization, idRecords:string[])
    + GroupName : string <<get>> <<set>>
    + CurrentYear : int <<get>> <<set>>
    + AvrMarkOfGroup : double <<get>> <<set>>
    + DeleteStudent(studentToDelete:Student) : void
    + AddNewStudentsToGroupFromScratch(idRecords:string[]) : void
    + ChangeSubjectsForStudents() : void
    + CreateCopyOfGroup() : Group
    + GetListOfSubjects(amountOfSubjects:int) : void
    + FindStudentsBySearchInGroup(name:string) : Student[]
    + GetEnumerator() : IEnumerator
}
struct StudentIEnumerator {
    + StudentIEnumerator(source:Group)
    + Current : object <<get>>
    + MoveNext() : bool
    + Reset() : void
}
IEnumerable <|-- Group
Group --> "UseId" Guid
Group --> "EnrollmentDateOfTheGroup" DateTime
Group --> "GroupSupervisor" Supervisor
Group --> "GroupSpecialization" Specialization
Group --> "StartDate" DateTime
Group +-- StudentIEnumerator
IEnumerator <|-- StudentIEnumerator
@enduml
