@startuml
struct Student {
    + Student(firstName:string, lastName:string, avgMark:int[,], dateOfBirth:DateTime)
    + StudentFirstName : string <<get>> <<set>>
    + StudentLastName : string <<get>> <<set>>
    + StudentAvgMark : double <<get>> <<set>>
    + GetAvgMarkOfTheStudent() : double
    + IsStudentExists(name:string) : bool
}
Student --> "StudentIdRecord" Guid
Student --> "StudentDateOfBirth" DateTime
@enduml
