@startuml
enum SubjectList {
    None,
    ComputerScience,
    ElectricalEngineering,
    MechanicalEngineering,
    CivilEngineering,
    ChemicalEngineering,
    InformationTechnology,
    AerospaceEngineering,
    BiomedicalEngineering,
    EnvironmentalEngineering,
    IndustrialEngineering,
    SoftwareEngineering,
    MaterialsScienceAndEngineering,
    Cybersecurity,
    RoboticsEngineering,
    DataScience,
}
@enduml
