@startuml

!include ./20240701_HW_Inheritence/UI.puml
!include ./20240701_HW_Inheritence/Retangle.puml
!include ./20240701_HW_Inheritence/Square.puml
!include ./20240701_HW_Inheritence/Point.puml
!include ./20240701_HW_Inheritence/Program.puml
!include ./20240701_HW_Inheritence/Quadrilateral.puml

!include ./20240701_HW_Inheritence/obj/Debug/net8.0/.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include ./20240701_HW_Inheritence/obj/Debug/net8.0/20240701_HW_Inheritence.GlobalUsings.g.puml
!include ./20240701_HW_Inheritence/obj/Debug/net8.0/20240701_HW_Inheritence.AssemblyInfo.puml

@enduml
