@startuml
struct GameLevelStructure {
    + heroHealthpoints : int
    + enemyHealthpoints : int
    + heroBlusterDamage : int
    + heroSpeed : ulong
    + enemyBlusterDamage : int
    + enemySpeed : ulong
    + enemyShotFrequensy : ulong
    + maxEnemiesOnScreen : int
}
GameLevelStructure --> "name" LevelEnums
@enduml
