@startuml
struct Spaceship {
    + id : int
    + symbol : char
    + healthPoint : int
    + spaceshipSpeed : ulong
}
Spaceship --> "bluster" BlusterProperty
Spaceship --> "spaceshipCoodinates" PositionOf
@enduml
